### ログイン
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "henoheno@mohe.zi",
  "password": "password"
}

### ログアウト
GET http://localhost:8080/logout

### メンバーの追加
POST http://localhost:8080/api/member
Content-Type: application/json

{
  "memberName": "へのへのもへじ1",
  "mailAddress": "henoheno1@mohe.zi",
  "password": "password",
  "role": "TEAM_MEMBER"
}

### メンバーの取得
GET http://localhost:8080/api/member/****

### メンバー情報の更新
PUT  http://localhost:8080/api/member
Content-Type: application/json

{
  "memberId": "****",
  "memberName": "へのへのもへじ,もへ",
  "mailAddress": "henoheno1@mohe.zi",
  "password": "password",
  "role": "TEAM_MEMBER"
}

### メンバーの削除
DELETE  http://localhost:8080/api/member/****

