### ログイン
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "henoheno1@mohe.zi",
  "password": "password"
}

### ログアウト
GET http://localhost:8080/logout

### メンバーの追加
POST http://localhost:8080/member
Content-Type: application/json

{
  "memberName": "へのへのもへじ",
  "mailAddress": "henoheno@mohe.zi",
  "password": "password",
  "role": "TEAM_MEMBER"
}

### メンバーの取得
GET http://localhost:8080/member/c0b5d997-3337-41c9-8857-367376c3d4bf

### メンバー情報の更新

### メンバーの削除
